# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do
  create_table :articles do |t|
    t.column :title, :string, :limit => 255
    t.column :permalink, :string, :limit => 255
    t.column :summary, :text
    t.column :description, :text
    t.column :created_at, :datetime
    t.column :updated_at, :datetime
    t.column :published_at, :datetime
  end

  create_table :tags do |t|
    t.column :title, :string, :limit => 255
  end

  create_table :taggings do |t|
    t.column :article_id, :integer
    t.column :tag_id, :integer
    t.column :position, :integer, :default => 1
  end
end
